version: "3"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  api:
    image: star-wars-api-image
    container_name: "api"
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - api-database
