server:
  port: 8085

spring:
  application:
    name: starwarsapi
  data:
    mongodb:
      uri: mongodb://localhost/planets
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

cache:
  timeoutSeconds: 300
  redisPort: 6379
  redisHost: localhost

integration:
  swapi: https://swapi.dev/api
