server:
  port: 8080

spring:
  application:
    name: starwarsapi
  data:
    mongodb:
      uri: mongodb://mongo/planets
  zipkin:
    base-url: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1

cache:
  timeoutSeconds: 300
  redisPort: 6379
  redisHost: redis

integration:
  swapi: https://swapi.dev/api
